### ISSUE TITLE
Dependency PHP-0Auth2 don't get cloned when using --recursive

### ISSUE THREAD

**Issue by buzzworkers** [mapkyca/KnownLinkedin#10]
git clone --recursive https://github.com/idno/KnownLinkedin

Cloning into 'KnownLinkedin'...
remote: Counting objects: 306, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 306 (delta 0), reused 0 (delta 0), pack-reused 303
Receiving objects: 100% (306/306), 42.08 KiB | 0 bytes/s, done.
Resolving deltas: 100% (130/130), done.
Checking connectivity... done.
Submodule 'LinkedIn/vendor/PHP-OAuth2' (git@github.com:adoy/PHP-OAuth2.git) registered for path 'LinkedIn/vendor/PHP-OAuth2'
Cloning into 'LinkedIn/vendor/PHP-OAuth2'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:adoy/PHP-OAuth2.git' into submodule path 'LinkedIn/vendor/PHP-OAuth2' failed

temporary fix : git clone https://github.com/adoy/PHP-OAuth2
into this folder IdnoPlugins/KnownLinkedin/LinkedIn/vendor/

then move Linkedin to /IdnoPlugins/
activate the plugin and you're good to go.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownLinkedin/issues/10" class="u-in-reply-to"></a>Are you using the latest version of the plugin? I've actually recently removed PHP-OAuth2 as a requirement, instead using Known's internal webservices library.

**Comment by buzzworkers** [comment]
moved to last version, problem gone indeed, ! thanks :+1:
