### ISSUE TITLE
Recent update may have removed icon?

### ISSUE THREAD

**Issue by chrisaldrich** [mapkyca/KnownLinkedin#16]
I recently updated Known to 0.8.2 and also updated the KnownLinkedin repository at the same time.  It appears that a recent update may have removed the UI Icons that typically appear in both the form and the final post:

![missing icon](https://cloud.githubusercontent.com/assets/5882943/8939637/6d967bea-351a-11e5-9e3a-04afe5d681a8.PNG)
![status update](https://cloud.githubusercontent.com/assets/5882943/8939640/7025a020-351a-11e5-8a61-9a206013a98e.PNG)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownLinkedin/issues/16" class="u-in-reply-to"></a>Seems to work for me (latest plugin + latest version of Known from Git)
