### ISSUE TITLE
Auth issues since upgrading to latest Known from git

### ISSUE THREAD

**Issue by srcr** [mapkyca/KnownLinkedin#17]
Since I upgrade Known from git yesterday publishing to LinkedIn is failing.
The message I'm getting is 

`Linkedin returned error code: 401 - Empty oauth2_access_token `

Some info from the log I get while posting is the following, not sure if it is related though.

`PHP message: PHP Notice:  Undefined index: syndication_account in IdnoPlugins/LinkedIn/Main.php on line 66`
`PHP message: PHP Notice:  Undefined index: syndication_account in IdnoPlugins/LinkedIn/Main.php on line 67`

I know the code isn't production, but I hope this could be fixed. I use it at least once a week.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownLinkedin/issues/17" class="u-in-reply-to"></a>Thanks for the heads-up. This may be an issue introduced by the retroactive POSSE code added in the recent builds... I'll investigate when I get a chance.

**Comment by rikmendes** [comment]
getting the same issue.

**Comment by srcr** [comment]
I hope @mapkyca will have sometime soon to fix this.

**Comment by mapkyca** [comment]
Had some time to look into this a bit, it looks like it's a problem with the upstream syndication code rather than this plugin. Closing in favour of idno/known#1350
