### ISSUE TITLE
Linkedin account connected but not displayed in the list of connected accounts

### ISSUE THREAD

**Issue by rikmendes** [mapkyca/KnownLinkedin#18]
I can POSSE to linkedin (at least the button is present) but when I go to /account/linkedin there is no visible connected accounts even though the connection seem to be OK : 
![screenshot_58](https://cloud.githubusercontent.com/assets/12155003/13555031/e99eb40a-e3b6-11e5-8972-26f116206b9e.png)

> Your account is currently connected to LinkedIn. Public updates, pictures, and posts that you publish here can be cross-posted to LinkedIn.

I remember a few month ago I could clearly see the linkedin account connected like I can for facebook or twitter. 
![screenshot_59](https://cloud.githubusercontent.com/assets/12155003/13555045/2635c7be-e3b7-11e5-8ad7-c950202528fe.png)

**Comment by rikmendes** [comment]
When I try to add a second or the same Linkedin account i get this : 
![screenshot_78](https://cloud.githubusercontent.com/assets/12155003/13882758/25d713da-ed27-11e5-8027-afb6826b01b1.png)

**Comment by mapkyca** [comment]
Check that $config->multi_syndication is true
