### ISSUE TITLE
Empty oauth2_access_token

### ISSUE THREAD

**Issue by rikmendes** [mapkyca/KnownLinkedin#19]
I got my Linkedin app & token correctly configured on Known backend
but still I'm getting this when I POSSE to Linkedin : 

> Linkedin returned error code: 401 - Empty oauth2_access_token

![screenshot_75](https://cloud.githubusercontent.com/assets/12155003/13882519/0ebcae0e-ed26-11e5-913d-a3208151ba4e.png)
![screenshot_76](https://cloud.githubusercontent.com/assets/12155003/13882527/15a13208-ed26-11e5-9f59-c0bab0a03e05.png)
![screenshot_77](https://cloud.githubusercontent.com/assets/12155003/13882531/195c9176-ed26-11e5-99a8-aa4833ba322a.png)

not sure what I can do to help you out debug this further.

**Comment by mapkyca** [comment]
Have you updated to the latest code?

**Comment by rikmendes** [comment]
Yes I think so..but just to double check let me git pull this repo once again.

**Comment by rikmendes** [comment]
I ended up by removing the whole Linkedin folder & git clone everything than cp to the IdnoPlugins folder, and now I can see which account is connected and I can successfully post to Linkedin.
i guess the version i had wasn't the latest code. this can be closed ! thanks for pointing me to the right direction :)
![screenshot_79](https://cloud.githubusercontent.com/assets/12155003/13898975/0b995c32-ede3-11e5-9811-4d82ce05df2a.png)
