### ISSUE TITLE
Issue reauthenticating

### ISSUE THREAD

**Issue by chrisaldrich** [mapkyca/KnownLinkedin#20]
I've had this plugin working for quite a while, though LinkedIn continually makes me reauthenticate.

Today when I try to reauthenticate to be able to POSSE there I get the following fatal error:

Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /htdocs/idno/IdnoPlugins/LinkedIn/LinkedIn/Client.php:31 - "Call to a member function getState() on boolean", on page stream.boffosocko.com/linkedin/callback?code=123456789ABCDEFG&state=123456789abcdefg

I doubt that it's an issue, but I saw this in Known v0.9.1 and again after upgrading to v0.9.2. Thoughts?

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/KnownLinkedin/issues/20" class="u-in-reply-to"></a>Interesting, that error implies that the plugin could not retrieve the Plugin object for the plugin.

I can't see a way that this *could* happen, possibly a database error?

*Maybe* try toggling the plugin..?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/mapkyca/KnownLinkedin/issues/20" class="u-in-reply-to"></a>Got it sorted. 

I think when I was updating, I installed a renamed "LinkedIn" parent folder rather than the child folder one level lower, which was the correct one. Apparently this allows just enough functionality so that all the pieces show up in the admin and settings interfaces, but that the plugin doesn't show up to be enabled/disabled in the plugin interface.
