### ISSUE TITLE
where are the updates published?

### ISSUE THREAD

**Issue by pierreozoux** [mapkyca/KnownLinkedin#22]
I use convoy (I guess it is using this behind the scene?)

I publish to linkedin, but just can't see it anywhere...
Do you have an idea?

Here is my profile:
https://www.linkedin.com/pulse/activities/pierre-ozoux+0_2fuPPEqrE76N-iKrI6zWzY?trk=prof-0-sb-rcnt-act-link

And indeed, https://blog.indie.host/2016/in-response-to-jwildeboerstatus776511196329566210 no links to linkedin.

Do you have an idea? Or should I report this to known directly for their convoy?

Thanks!

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/KnownLinkedin/issues/22" class="u-in-reply-to"></a>That's probably one for Convoy... 

LinkedIn change their api from time to time, plus there were some core Known api changes that forced an update to this plugin relatively recently. It's possible these haven't been merged back.

Either way, they'll have access to debug info which I don't :)
