### ISSUE TITLE
Nothing happens when going to Linkedin Account settings

### ISSUE THREAD

**Issue by hugoroy** [mapkyca/KnownLinkedin#8]
https://hugoroy.eu/account/linkedin/ gets a completely black page for me :-(

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownLinkedin/issues/8" class="u-in-reply-to"></a>It's working for me on my site. Do you get any errors in the php error log?

**Comment by hugoroy** [comment]
Yes.

    [Sat Jun 13 17:31:43 2015] [error] [client 2a01:e35:242d:1bb0:3e77:e6ff:fe18:ed03] PHP Warning:  require_once(/var/www/IdnoPlugins/KnownLinkedinPlugin/LinkedIn/vendor/PHP-OAuth2/src/OAuth2/Client.php): failed to open stream: No such file or directory in /var/www/IdnoPlugins/KnownLinkedinPlugin/LinkedIn/Main.php on line 237, referer: https://hugoroy.eu/account/settings/
    [Sat Jun 13 17:31:43 2015] [error] [client 2a01:e35:242d:1bb0:3e77:e6ff:fe18:ed03] PHP Fatal error:  require_once(): Failed opening required '/var/www/IdnoPlugins/KnownLinkedinPlugin/LinkedIn/vendor/PHP-OAuth2/src/OAuth2/Client.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/IdnoPlugins/KnownLinkedinPlugin/LinkedIn/Main.php on line 237, referer: https://hugoroy.eu/account/settings/

**Comment by benborges** [comment]
i fixed this by git cloning PHP-OAuth2 in the /IdnoPlugins/Linkedin/vendor folder

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownLinkedin/issues/8#issuecomment-111719981" class="u-in-reply-to"></a>Ya, you need to clone --recursive, since it uses git modules.

**Comment by hugoroy** [comment]
I got this

fatal: reference is not a tree: 27c0d7f65e25074ce1c4a916c798db3a29c85e9d
Unable to checkout '27c0d7f65e25074ce1c4a916c798db3a29c85e9d' in submodule path 'LinkedIn/vendor/PHP-OAuth2'

**Comment by mapkyca** [comment]
Interesting....

I think I'm going to move the module internal or use the known web services library directly...
