### ISSUE TITLE
can't POSSE to Linkedin even though Linkedin is connected ?

### ISSUE THREAD

**Issue by benborges** [mapkyca/KnownLinkedin#9]
This is the Linkedin connection tab http://i.imgur.com/NyBADFU.png
showing i'm connected to Linkedin (after having created the app etc..) 

my problem is that Linkedin does not appear anywhere as a POSSE target
and also it seems i can't disconnect my linkedin account now. 
no matter what i do, i can't disconnect the account, even by removing it's read/write access
directly in Linkedin App center. 

this is my post "status" screen : http://imgur.com/swGAqtn

**Comment by mapkyca** [comment]
Some of the permissions changed in Linkedin API... try the latest code...?

**Comment by benborges** [comment]
does a git pull inside the KnownLinkedin is enough to get the lastest code ?

**Comment by buzzworkers** [comment]
upgraded, and it's now displaying fine, just not in Bookmark type, not sure if it's intended or not..

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownLinkedin/issues/9" class="u-in-reply-to"></a>Yeah, bookmarks are currently not supported, but there's no reason why it shouldn't support them.

I'll add when I get time...
